let catalog, selected, revision, activeTab = 'presentation', documentZoom = 1;
const openGrades = new Set([4,5,6,7,8]); const selectedGrades = new Set(); const $ = (selector) => document.querySelector(selector);
const actions = [['portable','Portable HTML'],['presentationPdf','PDF prezentacji'],['worksheet','Karta pracy PDF'],['teacher','Materiały nauczyciela PDF'],['printPack','Pełny pakiet do druku']];
const documentTabs = [['worksheet','Karta pracy'],['teacher','Materiały nauczyciela'],['summary','Podsumowanie ucznia']];
const artifactNames = { portable: 'lekcja-portable.html', presentationPdf: 'prezentacja.pdf', worksheet: 'karta-pracy.pdf', teacher: 'materialy-nauczyciela.pdf', summary: 'podsumowanie-ucznia.pdf', printPack: 'pakiet-do-druku.pdf' };
function notice(text){const n=$('#status');n.textContent=text;n.style.display='block';setTimeout(()=>n.style.display='none',4000)}
function lessonWord(count){return count===1?'lekcja':count%10>=2&&count%10<=4&&!(count%100>=12&&count%100<=14)?'lekcje':'lekcji'}
async function load(){catalog=await fetch('/api/lessons').then(r=>r.json());renderCatalog();if(selected){selected=catalog.lessons.find(x=>x.directory===selected.directory);if(selected)renderWorkspace()}}
function renderGradeFilters(){const root=$('#grade-filters');root.textContent='';for(let grade=4;grade<=8;grade++){const tag=document.createElement('button');tag.className=`grade-filter grade-${grade}${selectedGrades.has(grade)?' active':''}`;tag.textContent=`Klasa ${grade}`;tag.setAttribute('aria-pressed',String(selectedGrades.has(grade)));tag.onclick=()=>{selectedGrades.has(grade)?selectedGrades.delete(grade):selectedGrades.add(grade);renderCatalog()};root.append(tag)}if(selectedGrades.size){const clear=document.createElement('button');clear.className='clear-filters';clear.textContent='× Wyczyść';clear.onclick=()=>{selectedGrades.clear();renderCatalog()};root.append(clear)}}
function renderCatalog(){renderGradeFilters();const filter=$('#filter').value.toLowerCase();const root=$('#catalog');root.textContent='';for(let grade=4;grade<=8;grade++){const items=catalog.lessons.filter(x=>x.grade===grade&&(!selectedGrades.size||selectedGrades.has(grade))&&x.title.toLowerCase().includes(filter));if(!items.length)continue;const box=document.createElement('details');box.className='grade';box.open=openGrades.has(grade);const summary=document.createElement('summary');summary.innerHTML=`<span>Klasa ${grade}</span><span class="lesson-count">${items.length} ${lessonWord(items.length)}</span>`;box.append(summary);box.addEventListener('toggle',()=>box.open?openGrades.add(grade):openGrades.delete(grade));for(const item of items){const b=document.createElement('button');b.dataset.grade=grade;b.className='lesson'+(selected?.directory===item.directory?' selected':'');b.textContent=`${String(item.sequence).padStart(2,'0')} · ${item.title}`;const small=document.createElement('small');small.textContent=item.valid?'kompletna lekcja':'wymaga kontroli';b.append(small);b.onclick=()=>{selected=item;activeTab='presentation';documentZoom=1;renderCatalog();renderWorkspace()};box.append(b)}root.append(box)}}
function renderWorkspace(){const w=$('#workspace');w.textContent='';const head=document.createElement('div');head.className='preview-head';head.innerHTML=`<h2>${selected.title}</h2>`;if(activeTab==='presentation'){const reload=document.createElement('button');reload.textContent='Odśwież podgląd';reload.onclick=()=>showPresentation();const open=document.createElement('button');open.className='open-preview';open.textContent='Otwórz w nowej karcie';open.onclick=()=>window.open(`/${selected.directory}/`,'_blank','noopener');head.append(reload,open)}w.append(head);const tabs=document.createElement('div');tabs.className='tabs';const choices=[['presentation','Prezentacja'],...documentTabs.filter(([kind])=>selected.capabilities[kind])];for(const [kind,label] of choices){const tab=document.createElement('button');tab.className=kind===activeTab?'active':'';tab.textContent=label;tab.onclick=()=>{activeTab=kind;renderWorkspace()};tabs.append(tab)}w.append(tabs);if(activeTab!=='presentation'){const zoom=document.createElement('div');zoom.className='document-zoom';const out=document.createElement('button');out.textContent='A−';out.disabled=documentZoom<=.8;out.onclick=()=>{documentZoom=Math.max(.8,+(documentZoom-.1).toFixed(1));renderWorkspace()};const value=document.createElement('span');value.textContent=`${Math.round(documentZoom*100)}%`;const reset=document.createElement('button');reset.textContent='100%';reset.onclick=()=>{documentZoom=1;renderWorkspace()};const add=document.createElement('button');add.textContent='A+';add.disabled=documentZoom>=1.5;add.onclick=()=>{documentZoom=Math.min(1.5,+(documentZoom+.1).toFixed(1));renderWorkspace()};zoom.append(out,value,reset,add);w.append(zoom)}const content=document.createElement('section');content.id='preview-content';w.append(content);if(activeTab==='presentation')showPresentation();else showDocument(activeTab);const box=document.createElement('div');box.className='actions';for(const [id,label] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>start(id);box.append(b)}if(selected.capabilities.summary){const b=document.createElement('button');b.textContent='Podsumowanie ucznia PDF';b.onclick=()=>start('summary');box.append(b)}w.append(box)}
function showPresentation(){const content=$('#preview-content');if(!content)return;content.textContent='';const frame=document.createElement('iframe');frame.className='preview';frame.title=`Podgląd: ${selected.title}`;frame.id='preview';frame.src=`/${selected.directory}/?ui-revision=${encodeURIComponent(selected.revision)}`;content.append(frame)}
async function showDocument(kind){const content=$('#preview-content');content.textContent='Wczytywanie materiału…';try{const response=await fetch(`/api/document?lesson=${encodeURIComponent(selected.directory)}&kind=${kind}`);const data=await response.json();if(!response.ok)throw new Error(data.error);const preview=document.createElement('article');preview.className='document-preview';preview.style.setProperty('--document-zoom',documentZoom);preview.innerHTML=data.html;for(const image of preview.querySelectorAll('img[src]'))image.src=new URL(image.getAttribute('src'),location.origin+data.baseUrl).href;content.textContent='';content.append(preview)}catch(error){content.textContent=`Nie udało się wczytać materiału: ${error.message}`}}
async function chooseCopy(action){if(!window.showSaveFilePicker)return null;try{return await window.showSaveFilePicker({suggestedName:artifactNames[action]||'eksport.pdf',types:[{description:'Plik eksportu',accept:{'application/pdf':['.pdf'],'text/html':['.html']}}]})}catch(error){if(error.name!=='AbortError')notice(`Nie udało się wybrać kopii: ${error.message}`);return null}}
async function saveCopy(handle,artifact){if(!handle||!artifact)return;const response=await fetch(`/${artifact}`);if(!response.ok)throw new Error('Nie udało się pobrać wygenerowanego pliku.');const writable=await handle.createWritable();await writable.write(await response.blob());await writable.close();notice('Zapisano dodatkową kopię na komputerze.')}
function downloadCopy(artifact){const link=document.createElement('a');link.href=`/${artifact}`;link.download='';link.click()}
async function start(action){const copyPromise=chooseCopy(action);const response=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lesson:selected.directory,action})});const job=await response.json();if(!response.ok)return notice(job.error);notice('Dodano zadanie do kolejki…');poll(job.id,copyPromise)}
async function poll(id,copyPromise){const job=await fetch(`/api/jobs/${id}`).then(r=>r.json());if(job.status==='queued'||job.status==='running'){notice(job.status==='queued'?'Czeka w kolejce…':'Generowanie…');return setTimeout(()=>poll(id,copyPromise),900)}if(job.status==='failed')return notice(`Błąd: ${job.error}`);const handle=await copyPromise;if(job.artifact){try{if(handle)await saveCopy(handle,job.artifact);else downloadCopy(job.artifact)}catch(error){notice(`Gotowe, ale kopia nie została zapisana: ${error.message}`)}}else notice('Operacja zakończona poprawnie.')}
async function checkChanges(){if(document.hidden)return;const next=await fetch('/api/revisions').then(r=>r.json());if(revision&&next.catalogRevision!==revision.catalogRevision){await load();notice('Katalog odświeżony.')}if(selected&&revision&&next.presentationRevisions[selected.directory]!==revision.presentationRevisions[selected.directory]){selected.revision=next.presentationRevisions[selected.directory];if(activeTab==='presentation')showPresentation();notice('Podgląd odświeżony.')}revision=next}
$('#refresh').onclick=load;$('#filter').oninput=renderCatalog;document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkChanges()});await load();revision=await fetch('/api/revisions').then(r=>r.json());setInterval(checkChanges,2000);
