let catalog, selected, revision; const $=s=>document.querySelector(s); const actions=[['portable','Portable HTML'],['presentationPdf','PDF prezentacji'],['worksheet','Karta pracy PDF'],['teacher','Materiały nauczyciela PDF'],['printPack','Cały pakiet do druku'],['renderCheck','Sprawdź render']];
function notice(text){const n=$('#status');n.textContent=text;n.style.display='block';setTimeout(()=>n.style.display='none',3500)}
async function load(){catalog=await fetch('/api/lessons').then(r=>r.json()); renderCatalog(); if(selected){selected=catalog.lessons.find(x=>x.directory===selected.directory); if(selected) renderWorkspace();}}
function renderCatalog(){const filter=$('#filter').value.toLowerCase(); const root=$('#catalog');root.textContent='';for(let grade=4;grade<=8;grade++){const items=catalog.lessons.filter(x=>x.grade===grade&&x.title.toLowerCase().includes(filter));if(!items.length)continue;const box=document.createElement('div');box.className='grade';box.innerHTML=`<h2>Klasa ${grade}</h2>`;for(const item of items){const b=document.createElement('button');b.className='lesson'+(selected?.directory===item.directory?' selected':'');b.textContent=`${String(item.sequence).padStart(2,'0')} · ${item.title}`;const small=document.createElement('small');small.textContent=item.valid?'kompletna lekcja':'wymaga kontroli';b.append(small);b.onclick=()=>{selected=item;renderCatalog();renderWorkspace()};box.append(b)}root.append(box)}}
function renderWorkspace(){const w=$('#workspace');w.textContent='';const head=document.createElement('div');head.className='preview-head';head.innerHTML=`<h2>${selected.title}</h2>`;const reload=document.createElement('button');reload.textContent='Odśwież podgląd';reload.onclick=()=>showFrame();const open=document.createElement('a');open.textContent='Otwórz w nowej karcie';open.target='_blank';open.href=`/${selected.directory}/`;head.append(reload,open);w.append(head);const frame=document.createElement('iframe');frame.className='preview';frame.title=`Podgląd: ${selected.title}`;frame.id='preview';w.append(frame);const box=document.createElement('div');box.className='actions';for(const [id,label] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>start(id);box.append(b)}if(selected.capabilities.summary){const b=document.createElement('button');b.textContent='Notatka ucznia PDF';b.onclick=()=>start('summary');box.append(b)}w.append(box);showFrame()}
function showFrame(){const frame=$('#preview');if(frame)frame.src=`/${selected.directory}/?ui-revision=${encodeURIComponent(selected.revision)}`}
async function start(action){const response=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lesson:selected.directory,action})});const job=await response.json();if(!response.ok)return notice(job.error);notice('Dodano zadanie do kolejki…');poll(job.id)}
async function poll(id){const job=await fetch(`/api/jobs/${id}`).then(r=>r.json());if(job.status==='queued'||job.status==='running'){notice(job.status==='queued'?'Czeka w kolejce…':'Generowanie…');return setTimeout(()=>poll(id),900)}if(job.status==='failed')return notice(`Błąd: ${job.error}`);if(job.artifact){notice('Gotowe — otwieram plik.');window.open(`/${job.artifact}`,'_blank')}else notice('Operacja zakończona poprawnie.')}
async function checkChanges(){if(document.hidden)return;const next=await fetch('/api/revisions').then(r=>r.json());if(revision&&next.catalogRevision!==revision.catalogRevision){await load();notice('Katalog odświeżony.')}if(selected&&revision&&next.presentationRevisions[selected.directory]!==revision.presentationRevisions[selected.directory]){selected.revision=next.presentationRevisions[selected.directory];showFrame();notice('Podgląd odświeżony.')}revision=next}
$('#refresh').onclick=load;$('#filter').oninput=renderCatalog;document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkChanges()});await load();revision=await fetch('/api/revisions').then(r=>r.json());setInterval(checkChanges,2000);