let lessons, tests, selected, revision, activeTab = 'presentation', documentZoom = 1, collection = 'lessons', config = { readOnly: false };
const openGrades = new Set([4,5,6,7,8]); const selectedGrades = new Set(); const $ = (selector) => document.querySelector(selector);
const lessonActions = [['portable','Portable HTML'],['presentationPdf','PDF prezentacji'],['worksheet','Karta pracy PDF'],['teacher','Materiały nauczyciela PDF'],['printPack','Pełny pakiet do druku']];
const documentTabs = [['worksheet','Karta pracy'],['teacher','Materiały nauczyciela'],['summary','Podsumowanie ucznia']];
const artifactNames = { portable: 'lekcja-portable.html', presentationPdf: 'prezentacja.pdf', worksheet: 'karta-pracy.pdf', teacher: 'materialy-nauczyciela.pdf', summary: 'podsumowanie-ucznia.pdf', printPack: 'pakiet-do-druku.pdf', testPdf: 'kartkowka.pdf' };
function notice(text){const n=$('#status');n.textContent=text;n.style.display='block';setTimeout(()=>n.style.display='none',4000)}
function materialWord(count){return collection==='tests'?(count===1?'kartkówka':count%10>=2&&count%10<=4&&!(count%100>=12&&count%100<=14)?'kartkówki':'kartkówek'):(count===1?'lekcja':count%10>=2&&count%10<=4&&!(count%100>=12&&count%100<=14)?'lekcje':'lekcji')}
function items(){return collection==='tests'?tests.tests:lessons.lessons}
async function load(){[lessons,tests]=await Promise.all([fetch('/api/lessons').then(r=>r.json()),fetch('/api/tests').then(r=>r.json())]);renderCatalog();if(selected){selected=items().find(x=>x.directory===selected.directory);if(selected)renderWorkspace()}}
function selectCollection(next){collection=next;selected=undefined;activeTab='presentation';documentZoom=1;selectedGrades.clear();$('#filter').value='';$('#show-lessons').setAttribute('aria-selected',String(next==='lessons'));$('#show-tests').setAttribute('aria-selected',String(next==='tests'));renderCatalog();$('#workspace').innerHTML='<p class="empty">Wybierz materiał z katalogu.</p>'}
function renderGradeFilters(){const root=$('#grade-filters');root.textContent='';for(let grade=4;grade<=8;grade++){const tag=document.createElement('button');tag.className=`grade-filter grade-${grade}${selectedGrades.has(grade)?' active':''}`;tag.textContent=`Klasa ${grade}`;tag.setAttribute('aria-pressed',String(selectedGrades.has(grade)));tag.onclick=()=>{selectedGrades.has(grade)?selectedGrades.delete(grade):selectedGrades.add(grade);renderCatalog()};root.append(tag)}if(selectedGrades.size){const clear=document.createElement('button');clear.className='clear-filters';clear.textContent='Wyczyść';clear.onclick=()=>{selectedGrades.clear();renderCatalog()};root.append(clear)}}
function renderCatalog(){renderGradeFilters();const filter=$('#filter').value.toLowerCase();const root=$('#catalog');root.textContent='';for(let grade=4;grade<=8;grade++){const gradeItems=items().filter(x=>x.grade===grade&&(!selectedGrades.size||selectedGrades.has(grade))&&x.title.toLowerCase().includes(filter));if(!gradeItems.length)continue;const box=document.createElement('details');box.className='grade';box.open=openGrades.has(grade);const summary=document.createElement('summary');summary.innerHTML=`<span>Klasa ${grade}</span><span class="lesson-count">${gradeItems.length} ${materialWord(gradeItems.length)}</span>`;box.append(summary);box.addEventListener('toggle',()=>box.open?openGrades.add(grade):openGrades.delete(grade));for(const item of gradeItems){const b=document.createElement('button');b.dataset.grade=grade;b.className='lesson'+(selected?.directory===item.directory?' selected':'');b.textContent=`${String(item.sequence).padStart(2,'0')} · ${item.title}`;if(collection==='lessons'){const small=document.createElement('small');small.textContent=item.valid?'kompletna lekcja':'wymaga kontroli';b.append(small)}b.onclick=()=>{selected=item;activeTab=collection==='tests'?'test':'presentation';documentZoom=1;renderCatalog();renderWorkspace()};box.append(b)}root.append(box)}}
function renderWorkspace(){const w=$('#workspace');w.textContent='';const head=document.createElement('div');head.className='preview-head';head.innerHTML=`<h2>${selected.title}</h2>`;if(collection==='lessons'&&activeTab==='presentation'){const reload=document.createElement('button');reload.textContent='Odśwież podgląd';reload.onclick=()=>showPresentation();const open=document.createElement('button');open.className='open-preview';open.textContent='Otwórz w nowej karcie';open.onclick=()=>window.open(`/${selected.directory}/`,'_blank','noopener');head.append(reload,open)}w.append(head);if(collection==='tests'){showTestDocument();if(!config.readOnly){const box=document.createElement('div');box.className='actions';const b=document.createElement('button');b.textContent='Drukuj / zapisz PDF';b.onclick=()=>start('testPdf');box.append(b);w.append(box)}return}const tabs=document.createElement('div');tabs.className='tabs';const choices=[['presentation','Prezentacja'],...documentTabs.filter(([kind])=>selected.capabilities[kind])];for(const [kind,label] of choices){const tab=document.createElement('button');tab.className=kind===activeTab?'active':'';tab.textContent=label;tab.onclick=()=>{activeTab=kind;renderWorkspace()};tabs.append(tab)}w.append(tabs);const content=document.createElement('section');content.id='preview-content';w.append(content);if(activeTab==='presentation')showPresentation();else showDocument(activeTab);if(!config.readOnly){const box=document.createElement('div');box.className='actions';for(const [id,label] of lessonActions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>start(id);box.append(b)}if(selected.capabilities.summary){const b=document.createElement('button');b.textContent='Podsumowanie ucznia PDF';b.onclick=()=>start('summary');box.append(b)}w.append(box)}}
function showPresentation(){const content=$('#preview-content');if(!content)return;content.textContent='';const frame=document.createElement('iframe');frame.className='preview';frame.title=`Podgląd: ${selected.title}`;frame.id='preview';frame.src=`/${selected.directory}/?ui-revision=${encodeURIComponent(selected.revision)}`;content.append(frame)}
function documentShell(html){const shell=document.createElement('div');shell.className='document-preview-shell';const preview=document.createElement('article');preview.className='document-preview';preview.style.setProperty('--document-zoom',documentZoom);preview.innerHTML=html;const zoom=document.createElement('div');zoom.className='document-zoom';for(const [label,change] of [['A−',-.2],['100%',0],['A+',.2]]){const button=document.createElement('button');button.textContent=label;button.disabled=(change<0&&documentZoom<=.6)||(change>0&&documentZoom>=2);button.onclick=()=>{documentZoom=change===0?1:Math.min(2,Math.max(.6,+(documentZoom+change).toFixed(1)));renderWorkspace()};zoom.append(button)}shell.append(preview,zoom);return shell}
async function showDocument(kind){const content=$('#preview-content');content.textContent='Wczytywanie materiału…';try{const response=await fetch(`/api/document?lesson=${encodeURIComponent(selected.directory)}&kind=${kind}`);const data=await response.json();if(!response.ok)throw new Error(data.error);const shell=documentShell(data.html);for(const image of shell.querySelectorAll('img[src]'))image.src=new URL(image.getAttribute('src'),location.origin+data.baseUrl).href;content.textContent='';content.append(shell)}catch(error){content.textContent=`Nie udało się wczytać materiału: ${error.message}`}}
async function showTestDocument(){const content=document.createElement('section');content.id='preview-content';content.textContent='Wczytywanie kartkówki…';$('#workspace').append(content);try{const response=await fetch(`/api/test-document?test=${encodeURIComponent(selected.directory)}`);const data=await response.json();if(!response.ok)throw new Error(data.error);content.textContent='';content.append(documentShell(data.html))}catch(error){content.textContent=`Nie udało się wczytać kartkówki: ${error.message}`}}
function exportFilename(action){return `${selected.title.replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim()} — ${artifactNames[action]||'eksport.pdf'}`}
async function chooseCopy(action){if(!window.showSaveFilePicker)return null;try{return await window.showSaveFilePicker({suggestedName:exportFilename(action),types:[{description:'Plik eksportu',accept:{'application/pdf':['.pdf'],'text/html':['.html']}}]})}catch(error){if(error.name!=='AbortError')notice(`Nie udało się wybrać kopii: ${error.message}`);return null}}
async function saveCopy(handle,artifact){if(!handle||!artifact)return;const response=await fetch(`/${artifact}`);if(!response.ok)throw new Error('Nie udało się pobrać wygenerowanego pliku.');const writable=await handle.createWritable();await writable.write(await response.blob());await writable.close();notice('Zapisano dodatkową kopię na komputerze.')}
function downloadCopy(artifact){const link=document.createElement('a');link.href=`/${artifact}`;link.download='';link.click()}
async function start(action){const copyPromise=chooseCopy(action);const body=collection==='tests'?{test:selected.directory,action}:{lesson:selected.directory,action};const response=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const job=await response.json();if(!response.ok)return notice(job.error);notice('Dodano zadanie do kolejki…');poll(job.id,copyPromise)}
async function poll(id,copyPromise){const job=await fetch(`/api/jobs/${id}`).then(r=>r.json());if(job.status==='queued'||job.status==='running'){notice(job.status==='queued'?'Czeka w kolejce…':'Generowanie…');return setTimeout(()=>poll(id,copyPromise),900)}if(job.status==='failed')return notice(`Błąd: ${job.error}`);const handle=await copyPromise;if(job.artifact){try{if(handle)await saveCopy(handle,job.artifact);else downloadCopy(job.artifact)}catch(error){notice(`Gotowe, ale kopia nie została zapisana: ${error.message}`)}}else notice('Operacja zakończona poprawnie.')}
async function checkChanges(){if(document.hidden)return;const next=await fetch('/api/revisions').then(r=>r.json());const changed=collection==='tests'?next.testCatalogRevision!==revision?.testCatalogRevision:next.catalogRevision!==revision?.catalogRevision;if(revision&&changed){await load();notice('Katalog odświeżony.')}if(selected&&revision&&collection==='tests'&&next.testDocumentRevisions[selected.directory]!==revision.testDocumentRevisions?.[selected.directory]){selected.revision=next.testDocumentRevisions[selected.directory];showTestDocument();notice('Kartkówka odświeżona.')}if(selected&&revision&&collection==='lessons'&&next.presentationRevisions[selected.directory]!==revision.presentationRevisions[selected.directory]){selected.revision=next.presentationRevisions[selected.directory];if(activeTab==='presentation')showPresentation();notice('Podgląd odświeżony.')}revision=next}
$('#refresh').onclick=load;$('#filter').oninput=renderCatalog;$('#show-lessons').onclick=()=>selectCollection('lessons');$('#show-tests').onclick=()=>selectCollection('tests');document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkChanges()});config=await fetch('/api/config').then(r=>r.json());await load();revision=await fetch('/api/revisions').then(r=>r.json());setInterval(checkChanges,2000);
